using Data.Entities;
using Microsoft.EntityFrameworkCore; 

namespace Data.Contexts;

public class DataContext(DbContextOptions<DataContext> options) : DbContext(options)
{
    public DbSet<ClientEntity> Clients { get; set; }
    public DbSet<UserEntity> Users { get; set; }
    public DbSet<EmployeeEntity> Employees { get; set; }
    public DbSet<ProjectEmployeeEntity> ProjectEmployees { get; set; }
    public DbSet<ProjectEntity> Projects { get; set; }
    public DbSet<StatusEntity> Statuses { get; set; }
    public DbSet<AddressEntity> Addresses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        //The date conversions below were suggested and generated by ChatGPT 4o, and I had som guidance from the same on configuring the one-to-many relationships. 
        modelBuilder.Entity<EmployeeEntity>()
            .Property(e => e.DateOfBirth)
            .HasConversion(v => v.ToString("yyyy-MM-dd"),
                           v => DateOnly.Parse(v));

        modelBuilder.Entity<ProjectEntity>()
            .Property(e => e.StartDate)
            .HasConversion(v => v.ToString("yyyy-MM-dd"),
                           v => DateOnly.Parse(v));

        modelBuilder.Entity<ProjectEntity>()
            .Property(e => e.EndDate)
            .HasConversion(v => v.ToString("yyyy-MM-dd"),
                           v => DateOnly.Parse(v));

        modelBuilder.Entity<ProjectEmployeeEntity>()
            .HasKey(x => new { x.ProjectId, x.EmployeeId });

        modelBuilder.Entity<ProjectEmployeeEntity>()
            .HasOne(pe => pe.Project)
            .WithMany(p => p.TeamMembers)
            .HasForeignKey(pe => pe.EmployeeId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<ProjectEmployeeEntity>()
            .HasOne(pe => pe.Employee)
            .WithMany(p => p.EmployeeProjects)
            .HasForeignKey(pe => pe.ProjectId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<ProjectEntity>()
            .HasOne(p => p.Status)
            .WithMany(s => s.Projects)
            .HasForeignKey(p => p.StatusId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<ProjectEntity>()
            .HasOne(p => p.Client)
            .WithMany(c => c.Projects)
            .HasForeignKey(p => p.ClientId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<UserEntity>()
            .HasIndex(u => u.Email)
            .IsUnique();

        modelBuilder.Entity<EmployeeEntity>()
            .HasIndex(e => e.Email)
            .IsUnique();

        modelBuilder.Entity<EmployeeEntity>()
            .HasOne(e => e.Address)
            .WithMany(ad => ad.Employees)
            .HasForeignKey(e => e.AddressId)
            .OnDelete(DeleteBehavior.Restrict);

        base.OnModelCreating(modelBuilder);
    }
}
